name: CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Mogak-Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ Mogak-Backend CI Success
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.CI_SUCCESS_IMAGE }}
          description: CI를 성공하였습니다.
          color: 00FF00
          username: Mogak-Backend CI
          url: https://github.com/TeamWSH-Moida/Mogak-Backend

      - name: SMS-Backend-CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗ Mogak-Backend CI Failed️
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.CI_FAIL_IMAGE }}
          description: CI를 실패하였습니다.
          color: FF0000
          username: Mogak-Backend CI
          url: https://github.com/TeamWSH-Moida/Mogak-Backend